# testing if this solved the error when importing Human class from human.py